# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-10 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0, verbose_name='父类编号')),
                ('ptype', models.CharField(default='', max_length=500, verbose_name='父类型')),
                ('key', models.CharField(default='', max_length=100, verbose_name='键')),
                ('value', models.CharField(default='', max_length=500, verbose_name='值')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remarks', models.TextField(default='', verbose_name='备注')),
                ('isdel', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(default=0, verbose_name='用户类型')),
                ('email', models.CharField(default='', max_length=50, verbose_name='邮箱')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('nickname', models.CharField(default='', max_length=25, verbose_name='用户昵称')),
                ('avatar', models.CharField(default='/images/default-default-avatar.png', max_length=25, verbose_name='用户头像')),
                ('password', models.CharField(default='e10adc3949ba59abbe56e057f20f883e', max_length=32, verbose_name='用户密码')),
                ('status', models.IntegerField(default=1, verbose_name='用户状态')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remarks', models.TextField(default='', verbose_name='备注')),
            ],
        ),
    ]
