# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
    ]
