# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0002_dictionary_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
