# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0003_auto_20171113_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(default=0, verbose_name='所属分类')),
                ('type', models.IntegerField(default=0, verbose_name='文章类型')),
                ('seotitle', models.CharField(default='', max_length=100, verbose_name='SEO标题')),
                ('seokeywords', models.CharField(default='', max_length=200, verbose_name='SEO关键词')),
                ('seodescription', models.CharField(default='', max_length=500, verbose_name='SEO描述')),
                ('sources', models.CharField(default='', max_length=50, verbose_name='来源')),
                ('filesurl', models.CharField(default='', max_length=500, verbose_name='文件链接')),
                ('imagesurl', models.CharField(default='', max_length=500, verbose_name='图片链接')),
                ('audiosurl', models.CharField(default='', max_length=500, verbose_name='音乐链接')),
                ('videosurl', models.CharField(default='', max_length=500, verbose_name='视频链接')),
                ('visits', models.IntegerField(default=0, verbose_name='浏览数')),
                ('agrees', models.IntegerField(default=0, verbose_name='赞数')),
                ('disagrees', models.IntegerField(default=0, verbose_name='踩数')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remarks', models.TextField(default='', verbose_name='备注')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('isdel', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
    ]
