# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0005_auto_20171113_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='sources',
            field=models.CharField(default='yii', max_length=50, verbose_name='来源'),
        ),
    ]
