# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0006_auto_20171113_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='remarks',
            field=models.TextField(default='', verbose_name='正文'),
        ),
    ]
