# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0007_auto_20171113_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(default=0, verbose_name='收藏类型编号')),
                ('type', models.CharField(default=0, max_length=500, verbose_name='收藏类型')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('imagesurl', models.CharField(default='', max_length=500, verbose_name='图片')),
                ('url', models.CharField(default='', max_length=500, verbose_name='链接')),
                ('visits', models.IntegerField(default=0, verbose_name='浏览数')),
                ('agrees', models.IntegerField(default=0, verbose_name='赞数')),
                ('disagrees', models.IntegerField(default=0, verbose_name='踩数')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remarks', models.TextField(default='', verbose_name='备注')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('isdel', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
    ]
