# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0009_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='sort',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.CharField(default='', max_length=500, verbose_name='内容'),
        ),
    ]
