# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0010_auto_20171114_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='remarks',
        ),
    ]
