# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0011_remove_feedback_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('imagesurl', models.CharField(default='', max_length=500, verbose_name='图片链接')),
                ('leading', models.CharField(default='', max_length=1000, verbose_name='引导语')),
                ('content', models.TextField(default='', verbose_name='正文')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
