# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0012_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='audiosurl',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='imagesurl',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='videosurl',
        ),
    ]
