# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0013_auto_20171114_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='imagesurl',
            field=models.CharField(default='', max_length=500, verbose_name='图片链接'),
        ),
    ]
