# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0014_essay_imagesurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='spiderid',
            field=models.CharField(default='', max_length=100, verbose_name='采集编号'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='category',
            field=models.CharField(default='', max_length=500, verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='type',
            field=models.CharField(default='', max_length=500, verbose_name='文章类型'),
        ),
    ]
