# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-07 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0016_agreelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='所在地'),
        ),
    ]
