# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-07 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0017_feedback_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreelog',
            name='status',
            field=models.IntegerField(default=0, verbose_name='结果0-默认1-顶2-踩'),
        ),
    ]
