# Generated by Django 2.0.8 on 2018-09-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0017_auto_20171215_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, verbose_name='说明')),
                ('imagesurl', models.CharField(default='', max_length=500, verbose_name='图片')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isdel', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
    ]
