# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0018_auto_20171207_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='logourl',
            field=models.CharField(default='', max_length=100, verbose_name='LOGO链接'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imagesurl',
            field=models.CharField(default='', max_length=500, verbose_name='BANNERS链接'),
        ),
    ]
