# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-13 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0020_auto_20171213_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='isdel',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='about',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
