# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-13 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0023_auto_20171213_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
