# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-13 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yii', '0024_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('typeid', models.IntegerField(default=0, verbose_name='类型编号')),
                ('type', models.CharField(default='', max_length=500, verbose_name='类型')),
                ('url', models.CharField(default='', max_length=100, verbose_name='链接')),
                ('content', models.TextField(default='', verbose_name='描述')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('isdel', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
    ]
